name: CI without cache

on: [push]


jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: v16.14.2

      - run: yarn install
      - run: curl https://cronitor.io/install-linux?sudo=1 -H "API-KEY: e5dfe9c2dffc40dab250917d11e92737"  | sh
      - cronitor discover

      ### - run: yarn test
